### ISSUE TITLE
You can try carbon

### ISSUE THREAD

**Issue by kuafuRace** [chilwaltanuj/achilles#1]
https://github.com/chilwaltanuj/achilles/blob/614b2159cd38ec0bd5e5839688ead7159eab755f/helper/time.go#L15

You can try this：
```go
import "github.com/golang-module/carbon/v2"

func GetUnixTimeInMs() int64 {
	return carbon.Now("Asia/Kolkata").TimestampMilli()
}

func GetUnixTimeInNanoSecond() int64 {
	return carbon.Now("Asia/Kolkata").TimestampNano()
}
```

**Comment by chilwaltanuj** [comment]
Thanks for suggestion.
Carbon was imported and  used for printing but not logging. It was in to do.
Done now.
